### ISSUE TITLE
新疆地区在地图上不显示

### ISSUE THREAD

**Issue by CherrieAI** [DQinYuan/chinese_province_city_area_mapper#15]
用draw_locations和echarts_draw这两个方法绘图都不显示新疆
测试了一下 对比新疆和武汉两个地方

`test = pd.DataFrame({'省':['新疆维吾尔自治区', '湖北省'], '市':['乌鲁木齐市', '武汉市'], '区':['新市区', '汉阳区']}, index=['a', 'b'])
draw_locations(test, 'test.html')`

发现武汉可以正常显示但新疆不行。
![image](https://user-images.githubusercontent.com/34235584/46597818-490a5b00-cb14-11e8-9f75-0d10333ec018.png)

**Comment by DQinYuan** [comment]
我今晚把这个bug修了，`pip install -U cpca`，更新到0.3.5版本，就可以了
