### ISSUE TITLE
对少数民族地区的地名映射存在问题

### ISSUE THREAD

**Issue by tim-lan** [DQinYuan/chinese_province_city_area_mapper#2]
比如输入字符串 "内蒙古阿拉善盟阿拉善左旗巴彦浩特镇"
输出 
     省                市                    区
0 None        阿拉善盟市      阿拉善左旗

1. 不能找到省级行政单位 内蒙古自治区
2. 会给市级行政单位盟的后面再加上一个市，造成重复和错误。

**Comment by DQinYuan** [comment]
我也发现了这个问题，正准备改

**Comment by tim-lan** [comment]
已经是很棒的工具了，谢谢。我直接用了查找替换把这个名称改过来。

**Comment by DQinYuan** [comment]
总算抽空把这个Bug解决，这个Issue我就先关了，欢迎提更多的错误用例

**Comment by DQinYuan** [comment]
除了这个还做了很多其他改动，甚至把模块名都给改了（改得更短了一些）

**Comment by tim-lan** [comment]
谢谢，早点休息
