### ISSUE TITLE
输入地址前的无效内容去除

### ISSUE THREAD

**Issue by ProHiryu** [DQinYuan/chinese_province_city_area_mapper#20]
请问我能够去除识别到的地址（第一个匹配到的词）之前的无效内容吗？

example："我的地址是XXXXXXX"，去除"我的地址是"这一块

**Comment by DQinYuan** [comment]
不好意思，暂时没有这个功能哈。如果不嫌麻烦的话可以写个程序在字符串中分别查找匹配出的省市区所属的位置，找到最前面的一个位置，然后将这个位置之前的字符删除

**Comment by ProHiryu** [comment]
是的，我也是这样想的，我在想如果可以的话还是挺不错的，就在程序里面加一个判断就好了，毕竟一般来说第一个匹配到的词一定是地址的开头（常识）

**Comment by ProHiryu** [comment]
如果要修改的话从哪个文件下手比较合适呢？

**Comment by DQinYuan** [comment]
https://github.com/DQinYuan/chinese_province_city_area_mapper/blob/master/chinese_province_city_area_mapper/infrastructure.py

这里的第26行
![匹配到了](https://user-images.githubusercontent.com/23725000/50076655-3d769700-021d-11e9-8551-98f1db2b1264.png)

**Comment by ProHiryu** [comment]
收到 谢谢～
