### ISSUE TITLE
某些单独的地级市无法被识别

### ISSUE THREAD

**Issue by rickzrn** [DQinYuan/chinese_province_city_area_mapper#22]
如果没有省份信息, 有些地级市无法被识别(甚至有省份信息也无法识别), 例如 "河北秦皇岛", "江西景德镇", "四川六盘水".

**Comment by rickzrn** [comment]
经核查, python2.7.x下代码可以使用,但是存在一定的问题. 上述问题在切换到3.5后得到解决.

**Comment by DQinYuan** [comment]
别关得这么快啊，最近比较忙，我还没来得及检查怎么回事呢😂

**Comment by rickzrn** [comment]
啊, 主要是在python2中的问题, 我记得有说过尽支持python3, 所以似乎这也不算是个bug
