### ISSUE TITLE
当传入地址含有省份命名的街道时，会被错误解析

### ISSUE THREAD

**Issue by LanjiaoGong** [DQinYuan/chinese_province_city_area_mapper#23]
举的例子 都是淘宝地址。

1、含陕西的，
上海 上海市 徐汇区 陕西南路666弄
<img width="365" alt="image" src="https://user-images.githubusercontent.com/13094018/53319399-6007e900-390d-11e9-8d69-8244069886ea.png">
上海 上海市 普陀区 长寿路街道 陕西北路澳门路
<img width="448" alt="image" src="https://user-images.githubusercontent.com/13094018/53319825-a90c6d00-390e-11e9-8960-30a598d3756e.png">
传入参数 cut=False 也不能正确解析。

2、含四川的，有的能解析正确，有的不能
解析错误：
重庆 重庆市 沙坪坝区 壮志路33号四川外国语大学山下400020：
<img width="538" alt="image" src="https://user-images.githubusercontent.com/13094018/53320270-1bca1800-3910-11e9-8f37-36d8e0575050.png">

解析正确：
上海 上海市 虹口区 四川北路街道 海泰时代大厦
<img width="458" alt="image" src="https://user-images.githubusercontent.com/13094018/53319646-0fdd5680-390e-11e9-9093-909cadc6b1d5.png">

**Comment by LanjiaoGong** [comment]
> 举的例子 都是淘宝地址。
> 
> 1、含陕西的，
> 上海 上海市 徐汇区 陕西南路666弄
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/13094018/53319399-6007e900-390d-11e9-8d69-8244069886ea.png">
> 上海 上海市 普陀区 长寿路街道 陕西北路澳门路
> <img alt="image" width="448" src="https://user-images.githubusercontent.com/13094018/53319825-a90c6d00-390e-11e9-8960-30a598d3756e.png">
> 传入参数 cut=False 也不能正确解析。
> 
> 2、含四川的，有的能解析正确，有的不能
> 解析错误：
> 重庆 重庆市 沙坪坝区 壮志路33号四川外国语大学山下400020：
> <img alt="image" width="538" src="https://user-images.githubusercontent.com/13094018/53320270-1bca1800-3910-11e9-8f37-36d8e0575050.png">
> 
> 解析正确：
> 上海 上海市 虹口区 四川北路街道 海泰时代大厦
> <img alt="image" width="458" src="https://user-images.githubusercontent.com/13094018/53319646-0fdd5680-390e-11e9-9093-909cadc6b1d5.png">

原因大概是市的优先级低，这样改一下就能正确解析了：
<img width="494" alt="image" src="https://user-images.githubusercontent.com/13094018/53323681-cb57b800-3919-11e9-8768-a9b800b3c1bc.png">

**Comment by DQinYuan** [comment]
感谢给出的错误用例，目前正在重构项目，会优化这些用例的

**Comment by gcxx** [comment]
这个问题我也遇到了 麻烦问一下有什么解决思路吗 能不能分享一下 先谢谢了

**Comment by DQinYuan** [comment]
这个问题已经解决了，请更新到最新版本（0.5.1）

```
pip install -U cpca
```

```python
>>> cpca.transform(["上海 上海市 普陀区 长寿路街道 陕西北路澳门路"])
     省    市    区              地址  adcode
0  上海市  市辖区  普陀区   长寿路街道 陕西北路澳门路  310107
```
