### ISSUE TITLE
“天津市”在全文匹配模式下，会被拆分成“天津市”、“津市市”

### ISSUE THREAD

**Issue by Octemull** [DQinYuan/chinese_province_city_area_mapper#42]
（1）正确情况
import cpca
values = ['天津市滨海新区']
df = cpca.transform(values, umap={}, pos_sensitive=False, cut=False)  

返回 结果为

     省    市    区    地址
0  天津市  天津市  津市市  滨海新区

（2）错误情况
import cpca
values = ['天津市滨海区']
df = cpca.transform(values, umap={}, pos_sensitive=False, cut=False)  

返回结果为

     省    市    区   地址
0  天津市  天津市  津市市  滨海区

**Comment by DQinYuan** [comment]
是有问题，我有空修复下

**Comment by DQinYuan** [comment]
该问题已在最新版本修复

```python
In [3]: cpca.transform(["天津市"], cut=False)
Out[3]:
     省        市             区 地址
0  天津市  天津市
```
