### ISSUE TITLE
对于地名中带有省类别的地址识别错误

### ISSUE THREAD

**Issue by IMYin** [DQinYuan/chinese_province_city_area_mapper#43]
详见图
![image](https://user-images.githubusercontent.com/11770037/63981050-141e4280-caf0-11e9-84d6-12d853ca0138.png)

**Comment by IMYin** [comment]
对于地址中有的路名带有省关键词，识别会错误，比如上海市**山西路**号，就会被识别出省份为山西省。

**Comment by DQinYuan** [comment]
这个问题已经解决了，请更新到最新版本（0.5.1）

```
pip install -U cpca
```

```python
>>> cpca.transform(["北京市石景山区老山东里"])
     省    市     区    地址  adcode
0  北京市  市辖区  石景山区  老山东里  110107
```
