### ISSUE TITLE
建议添加日志等级设置功能

### ISSUE THREAD

**Issue by Wistral** [DQinYuan/chinese_province_city_area_mapper#49]
https://github.com/DQinYuan/chinese_province_city_area_mapper/blob/a7d39b660db883f3dae84eea8d4d0338187b54ed/cpca/__init__.py#L212-L214

某些准确度要求较高的情况下, 需要在三级行政区重名时给出ERROR而不是warning(或抛出Exception)

**Comment by DQinYuan** [comment]
新版已经取消掉了日志
