### ISSUE TITLE
广州南沙在地址库且唯一但是提示无法映射？

### ISSUE THREAD

**Issue by johny123123** [DQinYuan/chinese_province_city_area_mapper#52]
>>> from cpca import area_map
>>> area_map.get_relational_addrs('南沙区')
[('广东省', '广州市', '南沙区')]
>>> location_str = ["南沙区","南沙"]
>>> df = cpca.transform(location_str)
WARNING:root: 无法映射, 建议添加进umap中
WARNING:root: 无法映射, 建议添加进umap中
>>>

**Comment by DQinYuan** [comment]
应该是分词的问题，把分词关掉就好了。

```python
cpca.transform(["南沙区"], cut=False)
```

```
     省        市           区            地址
1  广东省  广州市  南沙区  
```

**Comment by johny123123** [comment]
谢谢你的回复。
经过测试，关掉分词，确定可以正确映射。
等有时间再研究一下原因了，啊哈哈
