### ISSUE TITLE
大量转换时显示省略号

### ISSUE THREAD

**Issue by Alden9369486** [DQinYuan/chinese_province_city_area_mapper#53]
一次性大量转换，由于转换量比较大，中间显示的都是省略号，我想问一下我该怎么处理啊_

显示结果如下：
     省    市    区                          地址
0   河北省  保定市  涿州市              华阳路
1   江西省  宜春市  高安市              大城镇320国道旁
2   浙江省  杭州市  滨江区        建业路511号
3   江苏省  南京市  建邺区              庐山路188号
4                  上海市浦东新区世纪大道
..  ...  ...  ...                         ...
58  北京市  北京市  朝阳区             白家庄东里23号
59  河南省  郑州市  金水区             北三环索凌路交叉口
60  北京市  北京市  东城区        南竹杆胡同2号
61  北京市  北京市  西城区               三里河东路5号
62  广东省  广州市  天河区            花城大道68号

[63 rows x 4 columns]

**Comment by DQinYuan** [comment]
这不是真的省略，是为了方便看清楚，数据都在，通过

```pyton
df.to_csv(path, sep=' ', index=False)
```

就能写到一个 csv 文件中查看了
