### ISSUE TITLE
能提供爬取自中华人民共和国民政局全国行政区 爬取省 市 区 等的爬虫吗？

### ISSUE THREAD

**Issue by hepengfei-ml** [DQinYuan/chinese_province_city_area_mapper#55]

**Comment by good18** [comment]
根本不需要爬取，直接到民政局网站复制就行了

**Comment by juzj** [comment]
t = ['青岛市李沧区黑龙江中路629-143号网点']
    df = addressparser.transform(t, cut=True)
    print(df)
    """:arg
          省    市    区            地址
    0  黑龙江省  青岛市  李沧区  中路629-143号网点
    """

**Comment by juzj** [comment]
这个怎么解决

**Comment by DQinYuan** [comment]
最新版本已经将数据源改到 https://github.com/Vonng/adcode 了
