### ISSUE TITLE
'江西省南昌市新建区望城新区丰泽花园'无法解析出'新建区'

### ISSUE THREAD

**Issue by douchuan** [DQinYuan/chinese_province_city_area_mapper#68]
**江西省南昌市新建区望城新区丰泽花园** 无法解析出 **新建区**

使用如下方法，cut=False，才可以解析出‘新建区’，是jieba的问题吗？

`
location_str = ["浙江省杭州市下城区青云街40号3楼"]

import cpca
df = cpca.transform(location_str, cut=False)
df
`

**Comment by DQinYuan** [comment]
这个问题已经解决了，请更新到最新版本（0.5.1）

```
pip install -U cpca
```

```python
>>> cpca.transform(["江西省南昌市新建区望城新区丰泽花园"])
     省    市    区        地址  adcode
0  江西省  南昌市  新建区  望城新区丰泽花园  360112
```
