### ISSUE TITLE
transform返回dataframe的index缺失

### ISSUE THREAD

**Issue by liuyindyx** [DQinYuan/chinese_province_city_area_mapper#7]
强烈建议将transform函数最后一行pd.concat中ignore_index=True这个参数作为transforme的自定义参数，
让用户自己决定是否要输出原有的index。
大多数情况，我们需要相同的index以便对原有表格进行合并或者计算。

不知意下如何？

**Comment by DQinYuan** [comment]
不错的建议，我周末加一下，谢谢大佬

**Comment by DQinYuan** [comment]
index参数加上去了，`pip install -U cpca` 即可使用新的版本
