### ISSUE TITLE
识别报错:  在识别:  浙江省 织里镇 吴兴区织里镇织纺路731号中通快递2栋4号楼中间. 时报错了: AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by htycode** [DQinYuan/chinese_province_city_area_mapper#71]
执行下面这行代码
报错了:
df = cpca.transform(["浙江省 织里镇 吴兴区织里镇织纺路731号中通快递2栋4号楼中间"], open_warning, cut=False)

异常信息:
File "C:\Python37\lib\site-packages\cpca\__init__.py", line 198, in _fill_city
    if umap.get(pca.area):
AttributeError: 'bool' object has no attribute 'get'

**Comment by DQinYuan** [comment]
这个问题已经解决了，请更新到最新版本（0.5.1）

```
pip install -U cpca
```

```python
>>> cpca.transform(["浙江省 织里镇 吴兴区织里镇织纺路731号中通快递2栋4号楼中间"])
     省    市    区                     地址  adcode
0  浙江省  湖州市  吴兴区  织里镇织纺路731号中通快递2栋4号楼中间  330502
```
