### ISSUE TITLE
结巴分词精细度默认值设置为可调怎样？

### ISSUE THREAD

**Issue by CaptXiong** [DQinYuan/chinese_province_city_area_mapper#74]
这样一个地址“武汉东湖新技术开发区”，由于武汉后面没有市，jie.cut默认是cut_all为False，所有会提取不到，建议加个设置，并且设置默认为True，还没测试速度会慢多少，俺自己改了个先用着，作者觉得可以的话我就测测提个代码。

**Comment by waketzheng** [comment]
可行，建议提PR

**Comment by CaptXiong** [comment]
才发现新版已经没有jieba了，0.5.1已经可以识别我说的这个例子了

**Comment by DQinYuan** [comment]
做了一些更新，现在已经不进行分词了
