### ISSUE TITLE
如何有效识别“朝阳区”

### ISSUE THREAD

**Issue by vicsword11** [DQinYuan/chinese_province_city_area_mapper#78]
应该是北京市的 “朝阳区汉庭酒店大山子店“  
识别成了“吉林省  长春市  朝阳区  汉庭酒店大山子店  220104”
请问可以怎么调整映射关系

**Comment by waketzheng** [comment]
Show your code please

**Comment by DQinYuan** [comment]
一个比较 trick 的方法是到项目的 adcodes.csv 中把 吉林省朝阳区（220104） 的那一条数据给删了。后面我们会提供一个参数来自定义映射的

**Comment by DQinYuan** [comment]
最新版本（0.5.5及以上）已经可以了，见文档：
```python
cpca.transform(["朝阳区汉庭酒店大山子店"],umap={"朝阳区":"110105"})
#     省    市    区        地址  adcode
#0  北京市  市辖区  朝阳区  汉庭酒店大山子店  110105
```
