### ISSUE TITLE
新疆自动补全问题

### ISSUE THREAD

**Issue by TerribleLife** [DQinYuan/chinese_province_city_area_mapper#9]
我拿这个地址试了一下：“新疆阿克苏地区阿克苏市实验林场二队”，只能把新疆识别出来，后面的阿克苏地区和阿克苏市虽然mappers里面都有写，但识别不出来，看了下可能是infrastructure.py里面fillProvince的问题，加了一行
            if cls.province_country_mapper.get(word + "自治区"):
                return word + "自治区", True
然后在mappers.py里的province_country_mapper加了
      '新疆自治区':'中国'
再跑就没问题了。
因为代码还没仔细研究过，不知道改的有没有问题，反正结果是对了。。
大佬有空可以看一下这个问题吗

**Comment by DQinYuan** [comment]
我大概测了一下，感觉和你的现象不太一样：
```
from cpca import *
transform(["新疆阿克苏地区阿克苏市实验林场二队"])
```
输出是：
```
      区              市         省          地址
  阿克苏市                 新疆       实验林场二队
```
除了市其他都提取出来了。
当然，这里还是有问题的，我正在改。

**Comment by DQinYuan** [comment]
修好了，你更新一下再试试  `pip install -U cpca`

我自测的结果：
```
from cpca import *
transform(["新疆阿克苏地区阿克苏市实验林场二队"])
```
输出：
```
      区      市         省      地址
0  阿克苏市  阿克苏地区  新疆维吾尔自治区  实验林场二队
```
